# # # # # # # # # # # # # # # # # # # # # # # #
#  Core configuration, NOT live reloadable.   #
# # # # # # # # # # # # # # # # # # # # # # # #


# Available as `bot.config["<option>"]`
channel: myfavouritechannel
nick: mysupercoolbot
password: myverysecrettrippassword
server: wss://hack.chat/chat-ws
debug: false # Log more extensive exception information
