# # # # # # # # # # # # # # # # # # # # # # # #
#  Core configuration, NOT live reloadable.   #
# # # # # # # # # # # # # # # # # # # # # # # #


# Available as `bot.config["<option>"]`
channel: myfavouritechannel
nick: mysupercoolbot
password: myverysecrettrippassword
server: wss://hack.chat/chat-ws
debug: false # Log tracebacks and every event. If false,
             # logs only 'command' and 'whisper' events.
